### ISSUE TITLE
default well text

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [zakodium/react-well-plates#17]
Should we remove a check from "" or null or undefined to return an empty space on the grid

**Comment by stropitek** [comment]
I don't have the context that you have. What is the check doing? What effect would it have to remove it?

**Comment by targos** [comment]
if we don't want anything printed in the cell, currently we need to return a space or a Fragment. Returning null or empty string ends up in the position being printed in the cell by default.

**Comment by targos** [comment]
@Sebastien-Ahkrin we decided that a return of `undefined` should trigger the default text. Anything else should be used as-is.
