### ISSUE TITLE
customize header style

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [zakodium/react-well-plates#18]

**Comment by targos** [comment]
Add three callbacks:

```
headerClassName
headerStyle
headerText
```

They are called for each header cell, including the top-left empty one.
Callback receives an object with this shape:

```ts
interface {
  label: string;
  position: RowColumnPosition;
}
```

The position indexes start at `-1`.
Top-left corner: row: -1, column: -1
first column header (above first well): row: -1, column: 0
...

Also add the props to WellPicker (and just pass them to the child).
